In [1]:
import numpy as np

import keras 
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Conv2D, MaxPooling2D, SeparableConv2D
from keras.regularizers import l2
from keras.optimizers import SGD, RMSprop
from keras.utils import to_categorical
from keras.layers.normalization import BatchNormalization
from keras.utils.vis_utils import plot_model
from keras.layers import Input, GlobalAveragePooling2D
from keras import models
from keras.models import Model

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

import tensorflow

Using TensorFlow backend.


In [2]:
number_of_classes = 8
X, y = make_classification(n_samples=100000, n_features = 2304, n_informative = 200, n_classes = number_of_classes)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [3]:
n_values = np.max(y) + 1
y_train = np.eye(n_values)[y_train]
y_test = np.eye(n_values)[y_test]

In [4]:
X_train = X_train.reshape(75000,48,48,1)
X_test = X_test.reshape(25000,48,48,1)

In [6]:
print(X_train[0:10])

[[[[-7.56193236e-02]
   [ 2.76279490e-01]
   [-4.30673184e-01]
   ...
   [-6.10528727e-02]
   [ 6.67713618e-01]
   [-7.76433510e-01]]

  [[ 2.58451100e+00]
   [-1.57216678e+00]
   [ 4.43830833e-01]
   ...
   [-3.92981760e-01]
   [-5.85020597e-01]
   [-1.98596833e+00]]

  [[-8.27472596e-01]
   [ 1.31298612e-01]
   [ 7.55557012e-01]
   ...
   [ 7.55454703e-01]
   [ 5.63969160e-01]
   [ 6.24165400e-01]]

  ...

  [[ 3.14571175e-02]
   [-3.37070389e-01]
   [-3.22069236e-01]
   ...
   [-7.42691804e-01]
   [ 1.32155062e+00]
   [-5.88619563e+00]]

  [[ 4.14450416e-01]
   [-1.80858554e-01]
   [ 1.59800682e-01]
   ...
   [ 7.98974135e-01]
   [-1.38101618e+00]
   [-1.90659616e+00]]

  [[ 6.02942133e-01]
   [ 4.26921331e+00]
   [-1.64118726e+00]
   ...
   [-9.15749714e-01]
   [ 2.25968090e+00]
   [ 9.77781236e-01]]]


 [[[ 1.38459966e+00]
   [-5.25302628e-01]
   [-9.91503786e-01]
   ...
   [-8.78983011e-01]
   [ 3.81189192e-01]
   [-5.82436092e-01]]

  [[ 3.66056586e-01]
   [-5.37808636e-01]
   [

In [9]:
input_img = Input(shape=(48, 48, 1))

### 1st layer
layer_1 = Conv2D(10, (1,1), padding='same', activation='relu')(input_img)
layer_1 = Conv2D(10, (3,3), padding='same', activation='relu')(layer_1)

### 2nd layer
layer_2 = Conv2D(10, (1,1), padding='same', activation='relu')(input_img)
layer_2 = Conv2D(10, (5,5), padding='same', activation='relu')(layer_2)

### 3rd layer
layer_3 = MaxPooling2D((3,3), strides=(1,1), padding='same')(input_img)
layer_3 = Conv2D(10, (1,1), padding='same', activation='relu')(layer_3)

### Concatenate
mid_1 = keras.layers.concatenate([layer_1, layer_2, layer_3], axis = 3)

flat_1 = Flatten()(mid_1)

dense_1 = Dense(1200, activation='relu')(flat_1)
dense_2 = Dense(600, activation='relu')(dense_1)
dense_3 = Dense(150, activation='relu')(dense_2)

output = Dense(number_of_classes, activation='softmax')(dense_3)

In [10]:
model = Model([input_img], output)

In [11]:
plot_model(model, to_file='model.png', show_shapes=True, show_layer_names=True)

ImportError: Failed to import `pydot`. Please install `pydot`. For example with `pip install pydot`.

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test))